import img1 from "../images/couple-game-images/darwin-cruz.jpg";
import img2 from "../images/couple-game-images/imgCarrington.jpg";
import img3 from "../images/couple-game-images/imgChamin.jpg";
import img4 from "../images/couple-game-images/imgGomez.jpg";
import img5 from "../images/couple-game-images/imgPallares.jpg";
import img6 from "../images/couple-game-images/imgRendon.jpg";
import img7 from "../images/couple-game-images/imgRivera.jpg";
import img8 from "../images/couple-game-images/imgSouza.jpg";

const arrayCards = [
  {
    id: 1,
    image: img1,
    status: "down",
    title: "El amuleto de la buena suerte",
    author: "Darwin Cruz",
    size: "70 X 70cm",
    medium: "Óleo sobre tela",
  },
  {
    id: 2,
    image: img1,
    status: "down",
    title: "El amuleto de la buena suerte",
    author: "Darwin Cruz",
    size: "70 X 70cm",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 3,
    image: img2,
    status: "down",
    title: "Retrato de Enrique Alvarez Felix",
    author: "Leonora Carrington",
    size: "120 X 90cm",
    medium: "Óleo sobre tela",
  },
  {
    id: 4,
    image: img2,
    status: "down",
    title: "Retrato de Enrique Alvarez Felix",
    author: "Leonora Carrington",
    size: "120 X 90cm",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 5,
    image: img3,
    status: "down",
    title: "Lady Equus",
    author: "Carmen Chamin",
    size: "120 X 120cm",
    medium: "Óleo sobre tela",
  },
  {
    id: 6,
    image: img3,
    status: "down",
    title: "Lady Equus",
    author: "Carmen Chamin",
    size: "120 X 120cm",
    medium: "Óleo sobre tela",
  },
  {
    id: 7,
    image: img4,
    status: "down",
    title: "El Susurro del Pasado",
    author: "Mario Gomez",
    size: "40 x 47cm",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 8,
    image: img4,
    status: "down",
    title: "El Susurro del Pasado",
    author: "Mario Gomez",
    size: "40 x 47cm",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 9,
    image: img5,
    status: "down",
    title: "Isla Tortuga",
    author: "Marina Pallares",
    size: "200 x 300cm",
    medium: "Óleo sobre tela",
  },
  {
    id: 10,
    image: img5,
    status: "down",
    title: "Isla Tortuga",
    author: "Marina Pallares",
    size: "200 x 300cm",
    medium: "Óleo sobre tela",
  },
  {
    id: 11,
    image: img6,
    status: "down",
    title: "Avistamiento",
    author: "Jaime Rendon",
    size: "60 x 74cm",
    medium: "Acrílico sobre lienzo",
  },
  {
    id: 12,
    image: img6,
    status: "down",
    title: "Avistamiento",
    author: "Jaime Rendon",
    size: "60 x 74cm",
    medium: "Acrílico sobre lienzo",
  },
  {
    id: 13,
    image: img7,
    status: "down",
    title: "El Olvidado A.P.",
    author: "Arturo Rivera",
    size: "99 x 73cm",
    medium: "Acrílico y Óleo sobre lienzo",
  },
  {
    id: 14,
    image: img7,
    status: "down",
    title: "El Olvidado A.P.",
    author: "Arturo Rivera",
    size: "99 x 73cm",
    medium: "Acrílico y Óleo sobre lienzo",
  },
  {
    id: 15,
    image: img8,
    status: "down",
    title: "Pequeño Regalo",
    author: "Claudio Souza Pinto",
    size: "100 X 100cm         ",
    Medium: "Oleo sobre Lienzo",
  },
  {
    id: 16,
    image: img8,
    status: "down",
    title: "Pequeño Regalo",
    author: "Claudio Souza Pinto",
    size: "100 X 100cm         ",
    medium: "Oleo sobre Lienzo",
  },
];

export default arrayCards;
