import img1 from "../images/couple-game-images/darwin-cruz.jpg";
import img2 from "../images/couple-game-images/cristian-fitata.jpg";
import img3 from "../images/couple-game-images/mario-gomez.jpg";
import img4 from "../images/couple-game-images/guillermo-lorca.jpg";
import img5 from "../images/couple-game-images/kevin-sloan.jpg";
import img6 from "../images/couple-game-images/maria-helena.jpg";
import img7 from "../images/couple-game-images/rob-gonsalves.jpg";
import img8 from "../images/couple-game-images/Robert-Lyn-Nelson.jpg";

const arrayCards = [
  {
    id: 1,
    image: img1,
    status: "down",
    title: "El amuleto de la buena suerte",
    author: "Darwin Cruz",
    size: "70 X 70cm",
    medium: "Óleo en tela",
  },
  {
    id: 2,
    image: img1,
    status: "down",
    title: "El amuleto de la buena suerte",
    author: "Darwin Cruz",
    size: "70 X 70cm",
    medium: "Óleo en tela",
  },
  {
    id: 3,
    image: img2,
    status: "down",
    title: "Tristeza en el Bosque",
    author: "Cristian Fitata",
    size: "100 X 70cm",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 4,
    image: img2,
    status: "down",
    title: "Tristeza en el Bosque",
    author: "Cristian Fitata",
    size: "100 X 70cm",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 5,
    image: img3,
    status: "down",
    title: "Sin Titulo",
    author: "Mario Gomez",
    size: "Desconocido",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 6,
    image: img3,
    status: "down",
    title: "Sin Titulo",
    author: "Mario Gomez",
    size: "Desconocido",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 7,
    image: img4,
    status: "down",
    title: "Las Jardineritas",
    author: "Guillermo Lorca Garcia",
    size: "200 x 400cm",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 8,
    image: img4,
    status: "down",
    title: "Las Jardineritas",
    author: "Guillermo Lorca Garcia",
    size: "200 x 400cm",
    medium: "Óleo sobre lienzo",
  },
  {
    id: 9,
    image: img5,
    status: "down",
    title: "The Sleep of Reason",
    author: "Kevin Sloan",
    size: "137 x 121cm",
    medium: "Acrilico sobre lienzo",
  },
  {
    id: 10,
    image: img5,
    status: "down",
    title: "The Sleep of Reason",
    author: "Kevin Sloan",
    size: "137 x 121cm",
    medium: "Acrilico sobre lienzo",
  },
  {
    id: 11,
    image: img6,
    status: "down",
    title: "Remedios, la bella",
    author: "Helena Pérez Garcia",
    size: "40 x 52cm",
    medium: "Gouache y grafito sobre papel",
  },
  {
    id: 12,
    image: img6,
    status: "down",
    title: "Remedios, la bella",
    author: "Helena Pérez Garcia",
    size: "40 x 52cm",
    medium: "Gouache y grafito sobre papel",
  },
  {
    id: 13,
    image: img7,
    status: "down",
    title: "Flower Eclipse",
    author: "Rob Gonsalves",
    size: "Desconocido",
    medium: "Acrilico sobre lienzo",
  },
  {
    id: 14,
    image: img7,
    status: "down",
    title: "Flower Eclipse",
    author: "Rob Gonsalves",
    size: "Desconocido",
    medium: "Acrilico sobre lienzo",
  },
  {
    id: 15,
    image: img8,
    status: "down",
    title: "Imagine",
    author: "Robert Lyn Nelson",
    size: "70 X 70cm         ",
    Medium: "Oleo sobre Lienzo",
  },
  {
    id: 16,
    image: img8,
    status: "down",
    title: "Imagine",
    author: "Robert Lyn Nelson",
    size: "70 X 70cm         ",
    medium: "Oleo sobre Lienzo",
  },
];

export default arrayCards;
